import type {Experiment} from '../shared/types';

export function seedExperiments(): Experiment[] {
  return [
    {
      id: 'alpha',
      name: 'Primary query judgments',
      revision: 3,
      updatedAt: new Date(0).toISOString(),
      rules: [
        {
          id: 'r-rewrite-syn',
          kind: 'rewrite',
          matchType: 'exact',
          pattern: 'iphone 16 phone',
          replacement: 'iphone 16',
          scope: '*',
          priority: 10,
          enabled: true,
        },
        {
          id: 'r-rewrite-case-remap',
          kind: 'rewrite',
          matchType: 'regex',
          pattern: '^cheap (iphone) (case)$',
          replacement: '$2 for $1',
          scope: 'shop',
          priority: 5,
          enabled: true,
        },
        {
          id: 'r-pin-pro',
          kind: 'pin',
          matchType: 'exact',
          pattern: 'iphone 16',
          docId: 'iphone-16-pro',
          position: 1,
          scope: 'shop',
          priority: 20,
          enabled: true,
        },
        {
          id: 'r-demote-cases',
          kind: 'demote',
          matchType: 'regex',
          pattern: 'iphone',
          docPattern: 'case',
          action: 'downweight',
          factor: 0.2,
          scope: 'shop',
          priority: 10,
          enabled: true,
        },
        {
          id: 'r-filter-outlet',
          kind: 'demote',
          matchType: 'exact',
          pattern: 'cheap phone',
          docId: 'cheap-phones',
          action: 'filter',
          scope: '*',
          priority: 30,
          enabled: true,
        },
        {
          id: 'r-pin-outlet',
          kind: 'pin',
          matchType: 'exact',
          pattern: 'cheap phone',
          docId: 'cheap-phones',
          position: 1,
          scope: '*',
          priority: 5,
          enabled: true,
        },
      ],
      samples: [
        {id: 's1', text: 'iphone 16 phone', scope: 'shop'},
        {id: 's2', text: 'iphone 16', scope: 'shop'},
        {id: 's3', text: 'cheap phone', scope: 'web'},
        {id: 's4', text: 'iphone', scope: 'web'},
      ],
    },
    {
      id: 'beta',
      name: 'Rewrite loop probes',
      revision: 5,
      updatedAt: new Date(1000).toISOString(),
      rules: [
        {
          id: 'r-loop-a',
          kind: 'rewrite',
          matchType: 'exact',
          pattern: 'a',
          replacement: 'b',
          scope: '*',
          priority: 10,
          enabled: true,
        },
        {
          id: 'r-loop-b',
          kind: 'rewrite',
          matchType: 'exact',
          pattern: 'b',
          replacement: 'a',
          scope: '*',
          priority: 10,
          enabled: true,
        },
      ],
      samples: [
        {id: 's1', text: 'a', scope: 'web'},
        {id: 's2', text: 'iphone 16', scope: 'web'},
      ],
    },
  ];
}
